In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [73]:
df = pd.read_csv("SNA.csv")

In [74]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [75]:
df.tail()

      User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [76]:
df.shape

(400, 5)

In [77]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [78]:
from sklearn.preprocessing import LabelEncoder

In [79]:
df = df.drop(columns='User ID')

In [80]:
df.head()

   Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [81]:
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

In [82]:
df.head()

   Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

In [83]:
x = df.drop('Purchased',axis=1)
y = df['Purchased']

In [84]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [85]:
lr = LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [86]:
ypred = lr.predict(x_test)

In [87]:
from sklearn.metrics import accuracy_score

In [88]:
accuracy_score(ypred,y_test)

0.8875

In [89]:
CT = DecisionTreeClassifier()
CT.fit(x_train,y_train)

DecisionTreeClassifier()

In [90]:
y_tree_pred = CT.predict(x_test)

In [91]:
accuracy_score(y_test,y_tree_pred)

0.85